### PR TITLE
repaired lesson2 and added notes

### PR DESCRIPTION
**Pull request by Light--**
1, repaired the notebook for viewing
2, add notes about ipywidgets configuration and solve possible problem caused by widgets: https://github.com/fastai/fastai/issues/1539#issuecomment-505696380
3, correct json typos left by others

### CODE REVIEW

**Comment by Light--** [comment]
@sgugger Maestro, Do you know why i can't commit?

**Comment by jbharat** [comment]
Thanks. I started on the videos and found this issue on the 2nd lesson. I copied your solution and it worked.

**Comment by Light--** [comment]
> Thanks. I started on the videos and found this issue on the 2nd lesson. I copied your solution and it worked.

You are welcome. But i can not commit this pr. @jph00

**Comment by sgugger** [comment]
Thanks a lot. @Light-- if your auestion why you couldn't merge directly it's because only the maintainers of the repo can, after reviewing.
Also, don't forget to run the command `tools/run-after-git-clone` in the course-v3 cloned repo so that the automatic scripts that strip the notebooks from metadata is run, I re-stripped the notebook after merging your PR here.

**Comment by Light--** [comment]
> Thanks a lot. @Light-- if your auestion why you couldn't merge directly it's because only the maintainers of the repo can, after reviewing.
> Also, don't forget to run the command `tools/run-after-git-clone` in the course-v3 cloned repo so that the automatic scripts that strip the notebooks from metadata is run, I re-stripped the notebook after merging your PR here.

Many thanks for helping me! Now i know it's not that i can't commit, it's the metadata in the commited notebook should be stripped out(otherwise the pr will not pass the azure-pipelines check), am i right? Just want to make sure if it is the right steps for commiting pr: 

1. fork the repo and edit the notebook to correct; 
2. run the script ```tools/run-after-git-clone ``` to make the edited notebook with no metadata; 
3. commit the pr
4. one of the maintainers reviewed the pr and merge or reject

The reason why i got confused by "stripped out" azure-pipelines firstly is that, there are metadata in the original notebook already, i didn't change the metadata, all i did was edit the other contents, but the azure-pipelines still keep me from submitting. Haha :-D now i learned. Thank you.

**Pull request merged**
