### PR TITLE
Fix faulty logic in __call__ method of Runner class, fixes #370

### LINKED ISSUE #370: Questionable logic in __call__ method of runner class?
@jph00 @sgugger 

Please see `__call__` method of `Runner` class in notebook 05b_early_stopping.ipynb:

```python
class Runner():
    ...
    def __call__(self, cb_name):
        res = False
        for cb in sorted(self.cbs, key=lambda x: x._order): res = cb(cb_name) and res
        return res
```

Regardless of whether `cb(cb_name)` returns `True` or `False` `res` **will always equal `False`**. Is this intentional?

Shouldn't we return `True` if one of the callbacks returns `True` because it *intends to stop training*? If that was the intention we should change `res = cb(cb_name) and res` to `res = cb(cb_name) or res`

### PR DESCRIPTION
**Pull request by fg91**
Change `res = cb(cb_name) and res` to `res = cb(cb_name) or res`
so that `__call__` method does not always return `False` but returns
`True` if at least one of the callbacks returns `True`.

### CODE REVIEW

**Comment by jph00** [comment]
Thanks! There's some redundant stuff in this diff - could you please run the things mentioned here and re-submit, checking that the only thing in the diff is the actual change you made?: https://docs.fast.ai/dev/develop.html#things-to-run-after-git-clone

**Comment by jph00** [comment]
@fg91 bump!

**Comment by fg91** [comment]
Stripped the notebook.

Ps.: Sorry for the late reaction, started a new position which kept me busy.

**Comment by jph00** [comment]
Many thanks

**Comment by fg91** [comment]
The same mistake (`res = cb(cb_name) and res` should be `res = cb(cb_name) or res`) exists also in notebook 9b in which `Runner` is converted to `Learner`. Would you like me to prepare a pr?

One additional question:

in `Learner.fit` we do:

```python
for epoch in range(epochs):
    self.do_begin_epoch(epoch)
    if not self('begin_epoch'): self.all_batches()
```

However, `do_begin_epoch` already returned `return self('begin_epoch')` so we call all callbacks twice which is not necessary, correct?

Shell I change this to 

```python
if not self.do_begin_epoch(epoch): self.all_batches()
```

in the pr?

**Comment by jph00** [comment]
@fg91 perhaps you could try it and see if it works? If so, a PR would be welcome.

**Pull request merged**
