### PR TITLE
Add kubernetes deployment guide for Fastai

### PR DESCRIPTION
**Pull request by yubozhao**
Add the Kubernetes deployment guide for fastai.  Include how to build a model server with BentoML, build the model server docker image, and deploy to Kubernetes.

Feel free to ping me, if there are any questions I can help with.

### CODE REVIEW

**Comment by yubozhao** [comment]
hi @jph00, I would love to get your review and feedback on this deployment guide for Kubernetes.

**Comment by jph00** [comment]
Many apologies for the delay!

**Comment by gcucurull** [comment]
The url in the sidebar should be `/deployment_kubernetes_docker.html` instead of `/deployment_docker_kubernetes.html`. If you follow the link you get a 404 error because the content is not found.

This is the line that should be changed: https://github.com/fastai/course-v3/blob/master/docs/_data/sidebars/home_sidebar.yml#L152

**Comment by yubozhao** [comment]
@gcucurull Thanks for spotting it!  I think #508 537 is fixing it by change the doc name

**Pull request merged**
