### PR TITLE
Chinese translation for Lesson overviews

### PR DESCRIPTION
**Pull request by EmbraceLife**
chinese translation

### CODE REVIEW

**Comment by odysseus0** [comment]
Hey @stas00, do you know who is currently in charge of this repo? This PR is a followup to #235.

Now we have created the Chinese translation, we would need the person who built the website to find a way to introduce these contents.

**Comment by stas00** [comment]
Bu ji dao, @odysseus0. Usually Jeremy takes care of this repo. You can always see that from the commit logs.

**Comment by odysseus0** [comment]
עצוב. I somehow remembered that someone built/refined the first draft of the video player and the accompanying side window. Cannot remember who.

**Comment by zcaceres** [comment]
@odysseus0 i did the work on the player etc.

Depending on what the core team wants, would you like to do a PR that adds a language toggle to the right-side panel?

**Comment by odysseus0** [comment]
@zcaceres I would love to, but I am actually a total idiot in web programming. If you don't mind, could you please add the language toggle? 

If you check #235, you will see that Jeremy approved of the idea and merged that initial PR.

**Comment by jph00** [comment]
Sorry for the delay. Been a bit busy with the new course! Will talk to @zcaceres about this.

**Pull request merged**
