### PR TITLE
Docs: Update Google Cloud products and pricing

### PR DESCRIPTION
**Pull request by EwoutH**
- Updates the standard compute setup from `n1-highmem-8` to `n2d-highmem-8` (52 --> 64 GB memory, Intel --> AMD)
 - Updates the budget compute setup from `n1-highmem-4` to `n2d-highmem-4` (26 --> 32 GB memory, Intel --> AMD)
 - Updates both the standard P4 and budget K80 GPU to the cheaper and faster T4 GPU.
 - Updates storage pricing
 - Add an option for fast SSD storage

### CODE REVIEW

**Comment by EwoutH** [comment]
One question left: Do the models in this course scale over multiple GPUs? If so, we could advise two T4 TPUs for the standard option, since they are pretty cheap.

**Comment by EwoutH** [comment]
@jph00 What do you think?

**Comment by jph00** [comment]
Two GPUs are not recommended for the course.

**Comment by EwoutH** [comment]
Thanks for merging!

**Comment by danfrankj** [comment]
@jph00 @EwoutH 

As mentioned by google here: https://cloud.google.com/compute/docs/machine-types

image

GPUs are not supported on n2. Recommend reverting and perhaps adding a PR template with a required section for "how this was tested".  Do you guys want to take this on or I'm also happy to submit a PR.

**Comment by EwoutH** [comment]
Missed it, thanks for spotting, will submit an updated PR tomorrow

**Pull request merged**
