### PR TITLE
deploy guide for flask gunicorn docker

### PR DESCRIPTION
**Pull request by javismiles**
The objective of this article is to explain the instructions to deploy a Flask app that uses a model trained with the Fast.ai v2 library following an example in the upcoming book &quot;Deep Learning for Coders with fastai and PyTorch: AI Applications Without a PhD&quot; by Jeremy Howard and Sylvain Gugger.

The most important part of the project is testing a deployment process that combines a Flask app, the Gunicorn server, the Nginx server and a custom domain name with an SSL certificate, all installed on a dedicated server. Finally, you can also dockerize your app to make it portable and instructions to dockerize the app are also at the end of this article.

### CODE REVIEW

**Comment by jph00** [comment]
Great! Can you move the images into this repo and update the links? Please at-mention me when done.

**Comment by javismiles** [comment]
> Great! Can you move the images into this repo and update the links? Please at-mention me when done.

yes indeed, will get to it and let u know once is ready

**Comment by javismiles** [comment]
@jph00 I moved the only image of the article to docs/images/flask_gunicorn_nginx and updated the links to it, also added a bit more text, its ready ;) if you see anything else to be improved let me know

**Comment by jph00** [comment]
Great!

**Comment by javismiles** [comment]
ooops, looks like the image link is not correctly pointing to the image I uploaded to the repo:
https://github.com/fastai/course-v3/blob/master/docs/deployment_flask_gunicorn_docker.md

its pointing to:
https://github.com/fastai/course-v3/blob/master/images/flask_gunicorn_nginx/cutebear.jpg

in the file I put:
Image of cute bear

and the image is in:
https://github.com/fastai/course-v3/blob/master/docs/images/flask_gunicorn_nginx/cutebear.jpg

so I think I had to put /docs/images..etc instead of just /images
I had seen that the render logo of the render page had the link in the way I put it but they were using img src, and Im using a direct markdown link so that must make the difference

**Pull request merged**
