### PR TITLE
[DOC][AWS] Working example of setting up fast.ai without dl ami

### PR DESCRIPTION
**Pull request by krishnakalyan3**
AWS platform seems to be broken since Nov 11. (The optimized DL ami causes kernel to crash)

Updated the documentation to get started without DL AMI.

### CODE REVIEW

**Comment by jph00** [comment]
I don't think we should change the docs, but instead maybe add a comment to the top mentioning DLAMI is currently broken, and create (and link to) a new guide for AWS Ubuntu installation?

**Comment by krishnakalyan3** [comment]
@jph00 thank you for the review. Will do :)

**Comment by mohamedi** [comment]
Hi @krishnakalyan3 & @jph00  this review was never merged ?or I can't see them in Master branch or in the course site. if there is still a problem with Ubuntu 16 please deprecate existing guide and update to this guide. 

PS: I am starting with new updated MOOC version, so it will be helpful for me and other new students.

**Comment by jph00** [comment]
I'm not sure if the DLAMI is still broken. But see my request above for how I'd like to resolve this, if it is.

**Comment by mohamedi** [comment]
Got it 👍 so far in week 1, DLAMI is running good, if I or someone hit errors down the line. I will resolve as suggested.

**Pull request closed without merging**
