### PR TITLE
Made pascal notebook work and fixed model to get better results

### PR DESCRIPTION
**Pull request by Tsar**
Details are in the forum's topics:
1. Fix of unpad: https://forums.fast.ai/t/having-problems-running-pascal-ipynb-notebook/55155/3
2. Fix of model: https://forums.fast.ai/t/retina-net-notebook-merge-idx-issue/49939/11

Also coords transformation from ctwh to pixels was fixed (corrected formula for width and height) and data normalization was added.

### CODE REVIEW

**Comment by yijinlee** [comment]
Hi. I had a go at running your updated notebook, and it seems like you forgot to incorporate one change that you had in your [other file](https://github.com/Tsar/dl_research/blob/master/pascal_slice_0_2_and_normalize.ipynb)):

Changing ```z = learn.model.eval()(x)``` to ```z = learn.model.eval()(x.cuda())```

**Comment by jph00** [comment]
Thanks @Tsar . This is a little difficult for us to assess, since there's a few things going on, and we're deep in fastai v2 right now so we'd love help getting this integrated. Could you split it into 3 PRs? One which does normalization, one that does the padding stuff, and one for the other changes?

The normalization one is easy to pull since it's a simple and clear fix.

For the others, could you show the result of the change, and check on the forum that other folks find they also work better?

Many thanks!

**Comment by jph00** [comment]
@Tsar just a reminder about this PR - are you planning to follow up?

**Comment by Tsar** [comment]
> @Tsar just a reminder about this PR - are you planning to follow up?

Hi, Jeremy @jph00 !
I'm sorry for not answering for long time. I'm not sure that this RP has sence, because the main problem is still there: the results I reached using this notebook are still very-very far from state of the art...

**Pull request closed without merging**
